ALLOWED_TRANSITIONS = {
    "ORDER_RECEIVED": ["DOCUMENTS_IN_PROGRESS", "CANCELLED"],
    "DOCUMENTS_IN_PROGRESS": ["DOCUMENTS_READY", "CANCELLED"],
    "DOCUMENTS_READY": ["CUSTOMS_FILED", "CANCELLED"],
    "CUSTOMS_FILED": ["CUSTOMS_CLEARED", "CUSTOMS_HELD", "CANCELLED"],
    "CUSTOMS_HELD": ["CUSTOMS_FILED", "CANCELLED"],
    "CUSTOMS_CLEARED": ["SHIPPED", "CANCELLED"],
    "SHIPPED": ["IN_TRANSIT", "CANCELLED"],
    "IN_TRANSIT": ["ARRIVED", "CANCELLED"],
    "ARRIVED": ["DELIVERED", "CANCELLED"],
    "DELIVERED": ["COMPLETED", "CANCELLED"],
    "COMPLETED": [],
    "CANCELLED": []
}
